apiVersion: v1
kind: Secret
metadata:
  name: todoapp-db-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:Zxcvbnm123@postgres:5432/prostoapp?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: almuko/todoapp:latest
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todoapp-db-secret
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp
  namespace: default
spec:
  selector:
    app: todoapp
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todoapp-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - todoapp.compnet.kz
      secretName: todoapp-tls
  rules:
    - host: todoapp.compnet.kz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todoapp
                port:
                  number: 8081
